{
  "openapi": "3.1.0",
  "info": {
    "title": "API Reference",
    "version": "1.0.0",
    "contact": {}
  },
  "servers": [
    {
      "url": "https://api.sandbox.co.in",
      "description": "Production"
    },
    {
      "url": "https://test-api.sandbox.co.in",
      "description": "Test"
    }
  ],
  "paths": {
    "/kyc/digilocker-sdk/sessions/create": {
      "post": {
        "summary": "Create Session",
        "description": "Create Session",
        "operationId": "createSession",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-api-key",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "@entity": {
                    "type": "string",
                    "example": "in.co.sandbox.kyc.digilocker.sdk.session.request"
                  },
                  "doc_types": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "enum": [
                        "aadhaar",
                        "driving_license",
                        "pan"
                      ],
                      "description": "Document type",
                      "example": "aadhaar"
                    },
                    "example": [
                      "aadhaar",
                      "driving_license",
                      "pan"
                    ]
                  },
                  "flow": {
                    "type": "string",
                    "enum": [
                      "sign_in",
                      "sign_up"
                    ],
                    "description": "Flow type",
                    "example": "sign_in"
                  }
                }
              },
              "examples": {
                "Create Session": {
                  "value": {
                    "@entity": "in.co.sandbox.kyc.digilocker.sdk.session.request",
                    "doc_types": [
                      "aadhaar",
                      "driving_license",
                      "pan"
                    ],
                    "flow": "sign_in"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200 OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "@entity": {
                          "type": "string",
                          "example": "in.co.sandbox.kyc.digilocker.sdk.session"
                        },
                        "created_at": {
                          "type": "number",
                          "example": 1750331120324
                        },
                        "id": {
                          "type": "string",
                          "example": "0454f149-26d0-41ef-9f14-c54f4b5f7b70"
                        },
                        "status": {
                          "type": "string",
                          "example": "created"
                        }
                      }
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1750331120324
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "5ccad959-0bf4-4472-a3dd-d57e2b61b5a9"
                    }
                  }
                },
                "examples": {
                  "200 OK": {
                    "value": {
                      "code": 200,
                      "data": {
                        "@entity": "in.co.sandbox.kyc.digilocker.sdk.session",
                        "created_at": 1750331120324,
                        "id": "0454f149-26d0-41ef-9f14-c54f4b5f7b70",
                        "status": "created"
                      },
                      "timestamp": 1750331120324,
                      "transaction_id": "5ccad959-0bf4-4472-a3dd-d57e2b61b5a9"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400 Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 400
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid request body"
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1760426007752
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "f654ccdb-919f-486d-851d-0fc5d0050c17"
                    }
                  }
                },
                "examples": {
                  "400 Bad Request": {
                    "value": {
                      "code": 400,
                      "message": "Invalid request body",
                      "timestamp": 1760426007752,
                      "transaction_id": "f654ccdb-919f-486d-851d-0fc5d0050c17"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {}
        ]
      }
    },
    "/kyc/digilocker-sdk/sessions/{session_id}/status": {
      "get": {
        "summary": "Session Status",
        "description": "Session Status",
        "operationId": "sessionStatus",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-api-key",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "session_id",
            "in": "path",
            "required": true,
            "description": "Session ID from create session response",
            "schema": {
              "type": "string",
              "example": "a7fac865-61a9-4589-b80c...."
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 Session Created / 200 Session Expired / 200 Session Succeeded",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "@entity": {
                          "type": "string",
                          "example": "in.co.sandbox.kyc.digilocker.sdk.session"
                        },
                        "created_at": {
                          "type": "number",
                          "example": 1752579445983
                        },
                        "documents_consented": {
                          "type": "array",
                          "items": {
                            "type": "string",
                            "enum": [
                              "aadhaar",
                              "pan",
                              "driving_license"
                            ],
                            "description": "Document type",
                            "example": "aadhaar"
                          },
                          "example": [
                            "aadhaar",
                            "pan"
                          ]
                        },
                        "id": {
                          "type": "string",
                          "example": "839fd8a0-d645-42e1-a904-bb43353b0139"
                        },
                        "status": {
                          "type": "string",
                          "enum": [
                            "created",
                            "initialized",
                            "authorized",
                            "succeeded",
                            "failed",
                            "expired"
                          ],
                          "description": "Session status",
                          "example": "created"
                        },
                        "updated_at": {
                          "type": "number",
                          "example": 1752579445983
                        }
                      }
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1752580258171
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "800ff751-2191-4b7d-b20a-8301790a3e19"
                    }
                  }
                },
                "examples": {
                  "200 Session Created": {
                    "value": {
                      "code": 200,
                      "data": {
                        "@entity": "in.co.sandbox.kyc.digilocker.sdk.session",
                        "created_at": 1752579445983,
                        "id": "839fd8a0-d645-42e1-a904-bb43353b0139",
                        "status": "created"
                      },
                      "timestamp": 1752580258171,
                      "transaction_id": "800ff751-2191-4b7d-b20a-8301790a3e19"
                    }
                  },
                  "200 Session Expired": {
                    "value": {
                      "code": 200,
                      "data": {
                        "@entity": "in.co.sandbox.kyc.digilocker.sdk.session",
                        "created_at": 1752579445983,
                        "id": "839fd8a0-d645-42e1-a904-bb43353b0139",
                        "status": "expired",
                        "updated_at": 1752579445983
                      },
                      "timestamp": 1752580258171,
                      "transaction_id": "800ff751-2191-4b7d-b20a-8301790a3e19"
                    }
                  },
                  "200 Session Succeeded": {
                    "value": {
                      "code": 200,
                      "data": {
                        "@entity": "in.co.sandbox.kyc.digilocker.sdk.session",
                        "created_at": 1754990307997,
                        "documents_consented": [
                          "aadhaar",
                          "pan"
                        ],
                        "id": "5ed01344-d9b2-4b44-b0c7-e2901c834999",
                        "status": "succeeded",
                        "updated_at": 1754990726406
                      },
                      "timestamp": 1754991910851,
                      "transaction_id": "f29f1438-79e2-4090-854e-815d00620bd6"
                    }
                  }
                }
              }
            }
          },
          "521": {
            "description": "521 Data Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 521
                    },
                    "message": {
                      "type": "string",
                      "example": "Data not found for: 839fd8a0-d645-42e1-a904-bb43353b0139"
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1760428752393
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "8be099b1-8d19-457e-b907-5b825740d9cc"
                    }
                  }
                },
                "examples": {
                  "521 Data Not Found": {
                    "value": {
                      "code": 521,
                      "message": "Data not found for: 839fd8a0-d645-42e1-a904-bb43353b0139",
                      "timestamp": 1760428752393,
                      "transaction_id": "8be099b1-8d19-457e-b907-5b825740d9cc"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/kyc/digilocker-sdk/sessions/{session_id}/documents/{doc_type}": {
      "get": {
        "summary": "Get Document",
        "description": "Get Document",
        "operationId": "getDocument",
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-api-key",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "session_id",
            "in": "path",
            "required": true,
            "description": "Session ID from create session response",
            "schema": {
              "type": "string",
              "example": "a7fac865-61a9-4589-b80c...."
            }
          },
          {
            "name": "doc_type",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "aadhaar",
                "pan",
                "driving_license"
              ],
              "description": "Document type",
              "example": "aadhaar"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "files": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "@entity": {
                                "type": "string",
                                "example": "org.quicko.drive.file"
                              },
                              "metadata": {
                                "type": "object",
                                "properties": {
                                  "ContentType": {
                                    "type": "string",
                                    "example": "application/xml"
                                  },
                                  "LastModified": {
                                    "type": "string",
                                    "example": "09/05/2025"
                                  },
                                  "description": {
                                    "type": "string",
                                    "example": "Aadhaar Card"
                                  },
                                  "issuer": {
                                    "type": "string",
                                    "example": "Unique Identification Authority of India (UIDAI)"
                                  },
                                  "issuer_id": {
                                    "type": "string",
                                    "example": "in.gov.uidai"
                                  }
                                }
                              },
                              "size": {
                                "type": "number",
                                "example": 16598
                              },
                              "url": {
                                "type": "string",
                                "example": "https://in-co-sandbox-kyc-digilocker-dev.s3.ap-south-1.amazonaws.com/non-persistent/e385432b-575c-4b6f-8928-79136dbc0d4f/4b4bf7aa-f4da-47a8-9b32-895edfc03630/in.gov.uidai-ADHAR-0d5fe4d692c73e23c59a694eaaabc75a.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential={{vault:aws-access-key}}%2F20250708%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20250708T115214Z&X-Amz-Expires=3600&X-Amz-Signature=8cc4b0e8eb3794601c7fdb7e85f3a6bb3a8e1842403c8aeae5c05b7af03bdadb&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject"
                              }
                            }
                          },
                          "example": [
                            {
                              "@entity": "org.quicko.drive.file",
                              "metadata": {
                                "ContentType": "application/xml",
                                "LastModified": "09/05/2025",
                                "description": "Aadhaar Card",
                                "issuer": "Unique Identification Authority of India (UIDAI)",
                                "issuer_id": "in.gov.uidai"
                              },
                              "size": 16598,
                              "url": "https://in-co-sandbox-kyc-digilocker-dev.s3.ap-south-1.amazonaws.com/non-persistent/e385432b-575c-4b6f-8928-79136dbc0d4f/4b4bf7aa-f4da-47a8-9b32-895edfc03630/in.gov.uidai-ADHAR-0d5fe4d692c73e23c59a694eaaabc75a.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential={{vault:aws-access-key}}%2F20250708%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20250708T115214Z&X-Amz-Expires=3600&X-Amz-Signature=8cc4b0e8eb3794601c7fdb7e85f3a6bb3a8e1842403c8aeae5c05b7af03bdadb&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject"
                            }
                          ]
                        }
                      }
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1751975529441
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "a4d43b74-0f9c-480c-9300-f011100b674b"
                    }
                  }
                },
                "examples": {
                  "200 OK": {
                    "value": {
                      "code": 200,
                      "data": {
                        "files": [
                          {
                            "@entity": "org.quicko.drive.file",
                            "metadata": {
                              "ContentType": "application/xml",
                              "LastModified": "09/05/2025",
                              "description": "Aadhaar Card",
                              "issuer": "Unique Identification Authority of India (UIDAI)",
                              "issuer_id": "in.gov.uidai"
                            },
                            "size": 16598,
                            "url": "https://in-co-sandbox-kyc-digilocker-dev.s3.ap-south-1.amazonaws.com/non-persistent/e385432b-575c-4b6f-8928-79136dbc0d4f/4b4bf7aa-f4da-47a8-9b32-895edfc03630/in.gov.uidai-ADHAR-0d5fe4d692c73e23c59a694eaaabc75a.xml?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential={{vault:aws-access-key}}%2F20250708%2Fap-south-1%2Fs3%2Faws4_request&X-Amz-Date=20250708T115214Z&X-Amz-Expires=3600&X-Amz-Signature=8cc4b0e8eb3794601c7fdb7e85f3a6bb3a8e1842403c8aeae5c05b7af03bdadb&X-Amz-SignedHeaders=host&x-amz-checksum-mode=ENABLED&x-id=GetObject"
                          }
                        ]
                      },
                      "timestamp": 1751975529441,
                      "transaction_id": "a4d43b74-0f9c-480c-9300-f011100b674b"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400 Consent not provided",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 400
                    },
                    "message": {
                      "type": "string",
                      "example": "Consent for pan not provided"
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1760432035872
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "3d1d2d37-3179-4a3c-8397-2287084d1de1"
                    }
                  }
                },
                "examples": {
                  "400 Consent not provided": {
                    "value": {
                      "code": 400,
                      "message": "Consent for pan not provided",
                      "timestamp": 1760432035872,
                      "transaction_id": "3d1d2d37-3179-4a3c-8397-2287084d1de1"
                    }
                  }
                }
              }
            }
          },
          "521": {
            "description": "521 Data Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 521
                    },
                    "message": {
                      "type": "string",
                      "example": "Data not found for: 839fd8a0-d645-42e1-a904-bb43353b0139"
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1760428752393
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "8be099b1-8d19-457e-b907-5b825740d9cc"
                    }
                  }
                },
                "examples": {
                  "521 Data Not Found": {
                    "value": {
                      "code": 521,
                      "message": "Data not found for: 839fd8a0-d645-42e1-a904-bb43353b0139",
                      "timestamp": 1760428752393,
                      "transaction_id": "8be099b1-8d19-457e-b907-5b825740d9cc"
                    }
                  }
                }
              }
            }
          },
          "523": {
            "description": "523 Invalid Session Lifecycle",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "number",
                      "example": 523
                    },
                    "message": {
                      "type": "string",
                      "example": "Cannot get document due to invalid session lifecycle"
                    },
                    "timestamp": {
                      "type": "number",
                      "example": 1760431743347
                    },
                    "transaction_id": {
                      "type": "string",
                      "example": "031c9d24-99c4-49cb-b4ba-11e8c3630f9f"
                    }
                  }
                },
                "examples": {
                  "523 Invalid Session Lifecycle": {
                    "value": {
                      "code": 523,
                      "message": "Cannot get document due to invalid session lifecycle",
                      "timestamp": 1760431743347,
                      "transaction_id": "031c9d24-99c4-49cb-b4ba-11e8c3630f9f"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {}
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {}
  }
}